import base64
from pathlib import Path
from datetime import datetime

def generate_html_report(job_id, results, output_dir):
    """
    Generates a standalone HTML report with embedded Base64 images.
    """
    output_path = Path(output_dir) / "report.html"
    
    # helper to embed image
    def get_image_base64(img_path):
        if not img_path or not Path(img_path).exists():
            return ""
        with open(img_path, "rb") as f:
            encoded = base64.b64encode(f.read()).decode('utf-8')
            ext = Path(img_path).suffix[1:]
            return f"data:image/{ext};base64,{encoded}"

    png_url = results.get('png_url') # This is a relative URL like /api/results/ID/temp.png
    # We need the local path
    local_png_path = Path(output_dir) / "temperature_map.png"
    img_base64 = get_image_base64(local_png_path)
    max_temp = results.get('max_temp', results.get('max_temperature_K', 0))
    min_temp = results.get('min_temp', results.get('min_temperature_K', 0))
    solve_time = results.get('solve_time', results.get('solve_time_s', 0))
    converged = results.get('converged', True)

    html_content = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SimOps Thermal Report - {job_id}</title>
    <style>
        body {{
            font-family: 'Inter', -apple-system, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 40px 20px;
            background-color: #f9f9f9;
        }}
        .report-card {{
            background: white;
            padding: 40px;
            border-radius: 12px;
            box-shadow: 0 4px 20px rgba(0,0,0,0.08);
        }}
        h1 {{
            margin-top: 0;
            color: #1a1a1a;
            border-bottom: 2px solid #eee;
            padding-bottom: 10px;
        }}
        .meta {{
            font-size: 0.9em;
            color: #666;
            margin-bottom: 30px;
        }}
        .metrics {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            margin-bottom: 40px;
        }}
        .metric-item {{
            background: #f0f4f8;
            padding: 15px;
            border-radius: 8px;
        }}
        .metric-label {{
            font-size: 0.8em;
            text-transform: uppercase;
            color: #555;
            font-weight: bold;
        }}
        .metric-value {{
            font-size: 1.4em;
            font-weight: 700;
            color: #0056b3;
        }}
        .visualization {{
            margin-top: 40px;
            text-align: center;
        }}
        .visualization img {{
            max-width: 100%;
            height: auto;
            border-radius: 8px;
            border: 1px solid #ddd;
        }}
        .footer {{
            margin-top: 60px;
            font-size: 0.8em;
            color: #999;
            text-align: center;
        }}
        @media print {{
            body {{ background: white; padding: 0; }}
            .report-card {{ box-shadow: none; padding: 0; }}
        }}
    </style>
</head>
<body>
    <div class="report-card">
        <h1>SimOps Thermal Analysis Report</h1>
        <div class="meta">
            <div><strong>Job ID:</strong> {job_id}</div>
            <div><strong>Date:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</div>
        </div>

        <div class="metrics">
            <div class="metric-item">
                <div class="metric-label">Max Temperature</div>
                <div class="metric-value">{max_temp:.2f} K</div>
            </div>
            <div class="metric-item">
                <div class="metric-label">Min Temperature</div>
                <div class="metric-value">{min_temp:.2f} K</div>
            </div>
            <div class="metric-item">
                <div class="metric-label">Solve Time</div>
                <div class="metric-value">{solve_time:.2f} s</div>
            </div>
            <div class="metric-item">
                <div class="metric-label">Status</div>
                <div class="metric-value" style="color: {'#28a745' if converged else '#dc3545'}">
                    {'CONVERGED' if converged else 'FAILED'}
                </div>
            </div>
        </div>

        <div class="visualization">
            <h2>Temperature Distribution MAP</h2>
            <img src="{img_base64}" alt="Temperature Map">
        </div>

        <div class="footer">
            Generated by SimOps Engineer Engine. Standalone Report.
        </div>
    </div>
</body>
</html>
    """
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html_content)
    
    return str(output_path)
