"""Initial migration

Revision ID: f1836ef5e842
Revises: 
Create Date: 2026-01-09 18:07:12.530379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1836ef5e842'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mesh_results', sa.Column('modal_job_id', sa.String(length=100), nullable=True))
    op.add_column('mesh_results', sa.Column('modal_status', sa.String(length=20), nullable=True))
    op.add_column('mesh_results', sa.Column('modal_started_at', sa.DateTime(), nullable=True))
    op.add_column('mesh_results', sa.Column('modal_completed_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_mesh_results_modal_job_id'), 'mesh_results', ['modal_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mesh_results_modal_job_id'), table_name='mesh_results')
    op.drop_column('mesh_results', 'modal_completed_at')
    op.drop_column('mesh_results', 'modal_started_at')
    op.drop_column('mesh_results', 'modal_status')
    op.drop_column('mesh_results', 'modal_job_id')
    # ### end Alembic commands ###
